import React, { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { SearchBar } from '../components/SearchBar';
import { WordCard } from '../components/WordCard';
import { dictionaryStore } from '../lib/dictionaryStore';
import { DictionaryEntry } from '../types';
import { Frown, Sparkles, Loader2, Check, Edit2, Trash2 } from 'lucide-react';
import { defineWord } from '../lib/aiService';
import { Button } from '../components/ui/Button';
import { EntryEditor } from '../components/EntryEditor';

export const SearchResults: React.FC = () => {
  const [searchParams] = useSearchParams();
  const query = searchParams.get('q') || '';
  const [results, setResults] = useState<DictionaryEntry[]>([]);
  
  // AI Search State
  const [isAiSearching, setIsAiSearching] = useState(false);
  const [aiResult, setAiResult] = useState<DictionaryEntry | null>(null);
  const [aiError, setAiError] = useState(false);
  
  // Editing State
  const [isEditorOpen, setIsEditorOpen] = useState(false);

  useEffect(() => {
    if (!query) return;

    setAiResult(null);
    setAiError(false);
    setIsAiSearching(false);

    const matches = dictionaryStore.search(query);
    setResults(matches);

    if (matches.length === 0) {
      handleAiSearch(query);
    }
  }, [query]);

  const handleAiSearch = async (word: string) => {
    setIsAiSearching(true);
    try {
      const result = await defineWord(word);
      if (result) {
        setAiResult(result);
      } else {
        setAiError(true);
      }
    } catch (e) {
      setAiError(true);
    } finally {
      setIsAiSearching(false);
    }
  };

  const handleSaveAiResult = async () => {
    if (aiResult) {
      await dictionaryStore.addEntries([aiResult]);
      const matches = dictionaryStore.search(query);
      setResults(matches);
      setAiResult(null);
    }
  };

  const handleEditAiResult = () => {
    setIsEditorOpen(true);
  };

  const handleSaveEditedEntry = async (updatedEntry: DictionaryEntry) => {
    setAiResult(updatedEntry);
    setIsEditorOpen(false);
    
    await dictionaryStore.addEntries([updatedEntry]);
    const matches = dictionaryStore.search(query);
    setResults(matches);
    setAiResult(null);
  };

  const handleDiscard = () => {
    setAiResult(null);
    setAiError(true);
  };

  return (
    <div className="min-h-screen bg-slate-50">
      <div className="bg-white border-b border-slate-200">
        <div className="container mx-auto px-4 py-4">
           <SearchBar initialValue={query} variant="compact" />
        </div>
      </div>

      <div className="container mx-auto px-4 py-6 max-w-3xl">
        
        {results.length > 0 && (
          <div>
            <p className="text-slate-500 mb-4 text-sm">
              Found {results.length} result{results.length !== 1 ? 's' : ''} for <span className="font-semibold text-slate-900">"{query}"</span>
            </p>
            <div className="space-y-4">
              {results.map((entry, idx) => (
                <WordCard key={`${entry.headword}-${idx}`} entry={entry} />
              ))}
            </div>
          </div>
        )}

        {results.length === 0 && isAiSearching && (
          <div className="flex flex-col items-center justify-center py-16 text-center animate-pulse">
            <Sparkles className="w-10 h-10 text-purple-400 mb-3 animate-bounce" />
            <h3 className="text-base font-semibold text-slate-900">Consulting Gemini...</h3>
            <p className="text-slate-500 mt-1 text-sm">Generating a new definition for "{query}"</p>
          </div>
        )}

        {results.length === 0 && !isAiSearching && aiResult && (
          <div className="space-y-4 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="bg-purple-50 border border-purple-100 rounded-lg p-3 flex items-center justify-between">
               <div className="flex items-center gap-3">
                 <div className="bg-white p-1.5 rounded-full shadow-sm">
                    <Sparkles className="w-4 h-4 text-purple-600" />
                 </div>
                 <div>
                    <h3 className="font-semibold text-purple-900 text-sm">AI Generated Result</h3>
                    <p className="text-xs text-purple-700">This definition was generated by Gemini. Review it before saving.</p>
                 </div>
               </div>
            </div>

            <div className="relative">
                <div className="absolute -inset-0.5 bg-gradient-to-r from-purple-600 to-blue-600 rounded-xl opacity-20 blur"></div>
                <div className="relative">
                   <WordCard entry={aiResult} />
                </div>
            </div>

            <div className="flex flex-col sm:flex-row gap-2 justify-center pt-2">
                <Button onClick={handleSaveAiResult} className="bg-slate-900 hover:bg-slate-800 text-white gap-2 shadow-lg shadow-slate-200">
                    <Check className="w-4 h-4" />
                    Accept & Save
                </Button>
                <Button variant="outline" onClick={handleEditAiResult} className="gap-2">
                    <Edit2 className="w-4 h-4" />
                    Edit Definition
                </Button>
                <Button variant="ghost" onClick={handleDiscard} className="text-slate-400 hover:text-red-600 gap-2">
                    <Trash2 className="w-4 h-4" />
                    Discard
                </Button>
            </div>
          </div>
        )}

        {results.length === 0 && !isAiSearching && !aiResult && (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <div className="bg-slate-100 p-3 rounded-full mb-3">
              <Frown className="w-6 h-6 text-slate-400" />
            </div>
            <h3 className="text-base font-semibold text-slate-900">No definitions found</h3>
            <p className="text-slate-500 max-w-sm mt-1 text-sm">
              We couldn't find a match for "{query}" in our local database or generate one with AI. 
              Try checking your spelling.
            </p>
          </div>
        )}

        {aiResult && (
            <EntryEditor 
                isOpen={isEditorOpen}
                onClose={() => setIsEditorOpen(false)}
                initialEntry={aiResult}
                onSave={handleSaveEditedEntry}
                title={`Editing AI Draft: "${aiResult.headword}"`}
                saveLabel="Save to Dictionary"
            />
        )}
      </div>
    </div>
  );
};