import React from 'react';

export const TermsOfService: React.FC = () => {
  return (
    <div className="container mx-auto px-4 py-12 max-w-3xl">
      <h1 className="text-3xl font-bold text-slate-900 mb-6">Terms of Service</h1>
      <div className="prose prose-slate">
        <p className="text-slate-600 mb-4">Last updated: {new Date().toLocaleDateString()}</p>
        
        <h2 className="text-xl font-semibold text-slate-800 mt-8 mb-4">1. Acceptance of Terms</h2>
        <p className="text-slate-600 mb-4">
          By accessing and using the GEENMY dictionary, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
        </p>

        <h2 className="text-xl font-semibold text-slate-800 mt-8 mb-4">2. Use License</h2>
        <p className="text-slate-600 mb-4">
          Permission is granted to temporarily download one copy of the materials (information or software) on GEENMY's website for personal, non-commercial transitory viewing only.
        </p>

        <h2 className="text-xl font-semibold text-slate-800 mt-8 mb-4">3. Disclaimer</h2>
        <p className="text-slate-600 mb-4">
          The materials on GEENMY's website are provided on an 'as is' basis. While our definitions are empowered by advanced AI models, we make no warranties, expressed or implied, regarding the absolute accuracy of translations.
        </p>

        <h2 className="text-xl font-semibold text-slate-800 mt-8 mb-4">4. AI Content</h2>
        <p className="text-slate-600 mb-4">
          Portions of the content on this site are generated by artificial intelligence. Users should verify critical translations in professional contexts.
        </p>
      </div>
    </div>
  );
};